#!/bin/bash

set -e
umask 022

cd "$(dirname "$0")/.."

rootfs_dir="$(pwd)/build/rootfs/dir"

rm -fr "$rootfs_dir"

# Using dracut to gather the shared libraries
# from https://dracut.wiki.kernel.org/index.php/Main_Page
if ! test -x "$DRACUT_INSTALL"; then
    echo DRACUT_INSTALL unset or incorrect >&2
    exit 1
fi

inst() {
    [[ -e "${rootfs_dir}/${2:-$1}" ]] && return 0  # already there
    strip -s "$1" || true
    "$DRACUT_INSTALL" -D "$rootfs_dir" -l "$@"
}

mkdir -p "$rootfs_dir"/{bin,etc,proc/xen,sys,dev,tmp}

echo "Building initrd in $rootfs_dir"
inst build/busybox/busybox /bin/busybox
for i in \
    brctl \
    cat \
    cut \
    grep \
    head \
    ip \
    logger \
    ls \
    mdev \
    mkdir \
    mkfifo \
    mount \
    mv \
    rm \
    sed \
    seq \
    sh \
    sleep \
    sort \
    su \
    tee \
    timeout \
    touch \
    tr \
    udhcpd \
    setsid \
    stty \
    cttyhack
do
    ln -s busybox "$rootfs_dir/bin/$i"
done


if [[ -e "$PWD/build/qrexec/agent/qrexec-agent" ]]; then
    if [ -n "$LD_LIBRARY_PATH" ]; then
	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PWD/build/padist/lib:$PWD/build/padist/lib/pulseaudio:$PWD/build/qrexec/libqrexec"
    else
	export LD_LIBRARY_PATH="$PWD/build/padist/lib:$PWD/build/padist/lib/pulseaudio:$PWD/build/qrexec/libqrexec"
    fi
    inst build/padist/usr/local/bin/pulseaudio /bin/pulseaudio
    for mod in build/padist/lib/module-*.so; do
	inst "$mod" "/lib/$(basename "$mod")"
    done
fi

make DESTDIR="$PWD/build/qemu/install" -C build/qemu install
inst build/qemu/install/usr/bin/qemu-system-i386 /bin/qemu
inst build/qemu/build/pc-bios/optionrom/linuxboot_dma.bin /share/qemu/linuxboot_dma.bin
cp build/qemu/pc-bios/vgabios-cirrus.bin "$rootfs_dir"/share/qemu/vgabios-cirrus.bin
cp build/qemu/pc-bios/vgabios-stdvga.bin "$rootfs_dir"/share/qemu/vgabios-stdvga.bin

inst xenstore-read /bin/xenstore-read

inst helpers/vchan-socket-proxy /bin/vchan-socket-proxy
inst helpers/add-fd /bin/add-fd

if [[ -e "$PWD/build/qrexec/agent/qrexec-agent" ]]; then
inst helpers/qusb.sh /bin/qusb.sh
inst build/qrexec/agent/qrexec-agent /bin/qrexec-agent
inst build/qrexec/agent/qrexec-client-vm /bin/qrexec-client-vm
inst build/qrexec/agent/qrexec-fork-server /bin/qrexec-fork-server
echo "root:x:0:0:root:/root:/bin/sh" > "$rootfs_dir"/etc/passwd
echo "bus/usb/00[1-9]/00[2-9] 0:0 660 *sh /bin/qusb.sh" > "$rootfs_dir"/etc/mdev.conf 
fi

for i in write watch rm ls list; do
    ln -s xenstore-read "$rootfs_dir/bin/xenstore-$i"
done

# libgcc_s.so.1 is required by xenstore-watch for pthread:
for i in /lib{64,/x86_64-linux-gnu}/libgcc_s.so.1; do
    if [ -e "$i" ]; then
        inst "$i"
        break
    fi
done

inst "rootfs/qemu-ifup" "/etc/qemu-ifup"
inst "rootfs/qemu-ifdown" "/etc/qemu-ifdown"
inst "rootfs/init" "/init"

mkdir "$rootfs_dir"/lib.new
(find "$rootfs_dir"/{,usr/,usr/local/}lib{,64} -type f -print0 || true) | xargs -0r mv -t "$rootfs_dir"/lib.new/
rm -rf "${rootfs_dir:?}"/{,usr/,usr/local/}lib{,64}
IFS=:
for d in $LD_LIBRARY_PATH; do
(find "$rootfs_dir/$d" -type f -print0 || true) | xargs -0r mv -t "$rootfs_dir"/lib.new/
rm -rf "${rootfs_dir:?}/$d"
done
unset IFS
mv "$rootfs_dir"/lib{.new,}
# possible leftovers from local $LD_LIBRARY_PATH + dracut-install
rm -rf "${rootfs_dir:?}"/home
touch "$rootfs_dir"/etc/ld.so.conf
/sbin/ldconfig -r "$rootfs_dir" /lib
ln -s lib "$rootfs_dir"/lib64

if [[ -e "$PWD/build/libusb/.installed" ]]; then
ln -s tmp "$rootfs_dir"/var
mkdir -p "$rootfs_dir"/etc/qubes-rpc
mkdir -p "$rootfs_dir"/usr/lib/qubes
inst usbproxy/src/usb-import /usr/lib/qubes/usb-import
inst qrexec/lib/qubes-rpc-multiplexer /usr/lib/qubes/qubes-rpc-multiplexer
inst usbproxy/qubes-rpc/qubes.USBAttach /etc/qubes-rpc/qubes.USBAttach
chmod a+x "$rootfs_dir"/etc/qubes-rpc/qubes.USBAttach
fi

find "$rootfs_dir" -print0 | xargs -0 touch -ch -d @0
(
    cd "$rootfs_dir"
    find . -print0 | \
        LC_ALL=C sort -z | \
        cpio --null -R 0:0 -H newc -o
) | gzip -n -9 > build/rootfs/stubdom-linux-rootfs
